# Copyright © 2025 Cask Data, Inc.
#  Licensed under the Apache License, Version 2.0 (the "License"); you may not
#  use this file except in compliance with the License. You may obtain a copy of
#  the License at
#  http://www.apache.org/licenses/LICENSE-2.0
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
#  WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
#  License for the specific language governing permissions and limitations under
#  the License.

name: Maven Deploy

on:
  workflow_dispatch:
  push:
    branches: [ develop ]
  workflow_call:
    inputs:
      ref:
        required: true
        type: string

jobs:

  build-and-deploy:
    runs-on: cdapio-hub-k8-runner

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          path: e2e
          ref: ${{ inputs.ref }}

      - name: Cache
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-cdap-e2e-framework-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-cdap-e2e-framework

      - name: Submit Build to GCB
        id: gcb
        working-directory: cdap-e2e-tests
        run: |
          gcloud builds submit . \
            --config=cloudbuild.yaml \
            --project='cdapio-github-builds' \

